"""Form Runner and server-timed periods.

Revision ID: 080051a79ba7
Revises: 67c3592ae6c6
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "080051a79ba7"
down_revision = "67c3592ae6c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("uq_vehicles_company_id_id", "vehicles", ["company_id", "id"], unique=True)
    op.create_index("uq_drivers_company_id_id", "drivers", ["company_id", "id"], unique=True)
    op.create_index("uq_forms_company_id_id", "forms", ["company_id", "id"], unique=True)
    op.create_index("uq_form_versions_form_id_id", "form_versions", ["form_id", "id"], unique=True)
    op.create_index(
        "uq_form_fields_version_id_id", "form_fields", ["form_version_id", "id"], unique=True
    )
    op.create_table(
        "form_submissions",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("form_version_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=True),
        sa.Column("driver_id", sa.Uuid(), nullable=True),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'SUBMITTED')", name=op.f("ck_form_submissions_submission_status")
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "branch_id"],
            ["branches.company_id", "branches.id"],
            name=op.f("fk_form_submissions_company_id_branches"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "driver_id"],
            ["drivers.company_id", "drivers.id"],
            name=op.f("fk_form_submissions_company_id_drivers"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "form_id"],
            ["forms.company_id", "forms.id"],
            name=op.f("fk_form_submissions_company_id_forms"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "vehicle_id"],
            ["vehicles.company_id", "vehicles.id"],
            name=op.f("fk_form_submissions_company_id_vehicles"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_form_submissions_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_form_submissions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["form_id", "form_version_id"],
            ["form_versions.form_id", "form_versions.id"],
            name=op.f("fk_form_submissions_form_id_form_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_submissions")),
        sa.UniqueConstraint("id", "company_id", name="uq_submission_id_company"),
        sa.UniqueConstraint("id", "form_version_id", name="uq_submission_id_version"),
    )
    op.create_index(
        op.f("ix_form_submissions_company_id"), "form_submissions", ["company_id"], unique=False
    )
    op.create_table(
        "form_answers",
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("form_version_id", sa.Uuid(), nullable=False),
        sa.Column("field_id", sa.Uuid(), nullable=False),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("value_integer", sa.Integer(), nullable=True),
        sa.Column("value_decimal", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("value_boolean", sa.Boolean(), nullable=True),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("value_time", sa.Time(), nullable=True),
        sa.Column("value_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "value_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["form_version_id", "field_id"],
            ["form_fields.form_version_id", "form_fields.id"],
            name=op.f("fk_form_answers_form_version_id_form_fields"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_id", "company_id"],
            ["form_submissions.id", "form_submissions.company_id"],
            name="fk_answer_submission_company",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id", "form_version_id"],
            ["form_submissions.id", "form_submissions.form_version_id"],
            name="fk_answer_submission_version",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_answers")),
        sa.UniqueConstraint("id", "submission_id", "company_id", name=op.f("uq_form_answers_id")),
        sa.UniqueConstraint(
            "submission_id", "field_id", name=op.f("uq_form_answers_submission_id")
        ),
    )
    op.create_index(
        op.f("ix_form_answers_submission_id"), "form_answers", ["submission_id"], unique=False
    )
    op.create_table(
        "period_values",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("answer_id", sa.Uuid(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("status_key", sa.String(length=80), nullable=False),
        sa.Column("allow_concurrent", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(end_at IS NULL AND duration_seconds IS NULL) OR (end_at IS NOT NULL AND duration_seconds IS NOT NULL AND duration_seconds >= 0)",
            name=op.f("ck_period_values_period_duration"),
        ),
        sa.CheckConstraint(
            "end_at IS NULL OR end_at >= start_at", name=op.f("ck_period_values_period_chronology")
        ),
        sa.ForeignKeyConstraint(
            ["answer_id", "submission_id", "company_id"],
            ["form_answers.id", "form_answers.submission_id", "form_answers.company_id"],
            name=op.f("fk_period_values_answer_id_form_answers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_period_values")),
        sa.UniqueConstraint("answer_id", name=op.f("uq_period_values_answer_id")),
    )
    op.create_index(
        op.f("ix_period_values_company_id"), "period_values", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_period_values_submission_id"), "period_values", ["submission_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_period_values_submission_id"), table_name="period_values")
    op.drop_index(op.f("ix_period_values_company_id"), table_name="period_values")
    op.drop_table("period_values")
    op.drop_index(op.f("ix_form_answers_submission_id"), table_name="form_answers")
    op.drop_table("form_answers")
    op.drop_index(op.f("ix_form_submissions_company_id"), table_name="form_submissions")
    op.drop_table("form_submissions")
    op.drop_index("uq_form_fields_version_id_id", table_name="form_fields")
    op.drop_index("uq_form_versions_form_id_id", table_name="form_versions")
    op.drop_index("uq_forms_company_id_id", table_name="forms")
    op.drop_index("uq_drivers_company_id_id", table_name="drivers")
    op.drop_index("uq_vehicles_company_id_id", table_name="vehicles")
    # ### end Alembic commands ###
