"""subform_relations

Revision ID: 2fa3d7f56571
Revises: 080051a79ba7
Create Date: 2026-09-11 03:19:36.090077
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "2fa3d7f56571"
down_revision: Union[str, None] = "080051a79ba7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "submission_relations",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("parent_submission_id", sa.Uuid(), nullable=False),
        sa.Column("child_submission_id", sa.Uuid(), nullable=False),
        sa.Column("parent_version_id", sa.Uuid(), nullable=False),
        sa.Column("relation_field_id", sa.Uuid(), nullable=False),
        sa.Column("request_key", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "parent_submission_id <> child_submission_id",
            name=op.f("ck_submission_relations_relation_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["child_submission_id", "company_id"],
            ["form_submissions.id", "form_submissions.company_id"],
            name="fk_relation_child_company",
        ),
        sa.ForeignKeyConstraint(
            ["parent_submission_id", "company_id"],
            ["form_submissions.id", "form_submissions.company_id"],
            name="fk_relation_parent_company",
        ),
        sa.ForeignKeyConstraint(
            ["parent_submission_id", "parent_version_id"],
            ["form_submissions.id", "form_submissions.form_version_id"],
            name="fk_relation_parent_version",
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id", "relation_field_id"],
            ["form_fields.form_version_id", "form_fields.id"],
            name="fk_relation_field_version",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission_relations")),
        sa.UniqueConstraint(
            "child_submission_id", name=op.f("uq_submission_relations_child_submission_id")
        ),
        sa.UniqueConstraint(
            "parent_submission_id",
            "request_key",
            name=op.f("uq_submission_relations_parent_submission_id"),
        ),
    )
    op.create_index(
        op.f("ix_submission_relations_company_id"),
        "submission_relations",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submission_relations_parent_submission_id"),
        "submission_relations",
        ["parent_submission_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_submission_relations_parent_submission_id"), table_name="submission_relations"
    )
    op.drop_index(op.f("ix_submission_relations_company_id"), table_name="submission_relations")
    op.drop_table("submission_relations")
    # ### end Alembic commands ###
