"""form_builder

Revision ID: 67c3592ae6c6
Revises: 753a4265440b
Create Date: 2026-09-08 19:42:20.861913
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "67c3592ae6c6"
down_revision: Union[str, None] = "753a4265440b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forms",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="formstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_forms_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forms")),
        sa.UniqueConstraint("company_id", "code", name=op.f("uq_forms_company_id")),
    )
    op.create_index(op.f("ix_forms_company_id"), "forms", ["company_id"], unique=False)
    op.create_table(
        "form_versions",
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("schema_hash", sa.String(length=64), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_form_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["form_id"], ["forms.id"], name=op.f("fk_form_versions_form_id_forms")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_versions")),
        sa.UniqueConstraint("form_id", "version", name=op.f("uq_form_versions_form_id")),
    )
    op.create_index(op.f("ix_form_versions_form_id"), "form_versions", ["form_id"], unique=False)
    op.create_index(
        "uq_form_versions_draft",
        "form_versions",
        ["form_id"],
        unique=True,
        postgresql_where=sa.text("published_at IS NULL"),
        sqlite_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "form_fields",
        sa.Column("form_version_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column(
            "field_type",
            sa.Enum(
                "TEXT",
                "INTEGER",
                "DECIMAL",
                "DATE",
                "TIME",
                "DATETIME",
                "BOOLEAN",
                "SINGLE_SELECT",
                "MULTI_SELECT",
                "VEHICLE_REFERENCE",
                "DRIVER_REFERENCE",
                "CUSTOMER_REFERENCE",
                "JOBSITE_REFERENCE",
                "PHOTO",
                "FILE",
                "PERIOD",
                "CALCULATED",
                "SUBFORM",
                name="fieldtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["form_version_id"],
            ["form_versions.id"],
            name=op.f("fk_form_fields_form_version_id_form_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_fields")),
        sa.UniqueConstraint("form_version_id", "key", name=op.f("uq_form_fields_form_version_id")),
    )
    op.create_index(
        op.f("ix_form_fields_form_version_id"), "form_fields", ["form_version_id"], unique=False
    )
    install_immutability_guards()
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION protect_published_fields() CASCADE")
        op.execute("DROP FUNCTION protect_published_version() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_form_fields_form_version_id"), table_name="form_fields")
    op.drop_table("form_fields")
    op.drop_index(
        "uq_form_versions_draft",
        table_name="form_versions",
        postgresql_where=sa.text("published_at IS NULL"),
        sqlite_where=sa.text("published_at IS NULL"),
    )
    op.drop_index(op.f("ix_form_versions_form_id"), table_name="form_versions")
    op.drop_table("form_versions")
    op.drop_index(op.f("ix_forms_company_id"), table_name="forms")
    op.drop_table("forms")
    # ### end Alembic commands ###


def install_immutability_guards():
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
        CREATE FUNCTION protect_published_version() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.published_at IS NOT NULL THEN
                RAISE EXCEPTION 'published_version_immutable' USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END $$
        """)
        op.execute("""
        CREATE TRIGGER published_version_guard BEFORE UPDATE OR DELETE ON form_versions
        FOR EACH ROW EXECUTE FUNCTION protect_published_version()
        """)
        op.execute("""
        CREATE FUNCTION protect_published_fields() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE parent_id uuid; prior_id uuid; version_row record;
        BEGIN
            IF TG_OP <> 'DELETE' THEN parent_id := NEW.form_version_id; END IF;
            IF TG_OP <> 'INSERT' THEN prior_id := OLD.form_version_id; END IF;
            FOR version_row IN SELECT published_at FROM form_versions
                WHERE id IN (parent_id, prior_id) ORDER BY id FOR UPDATE
            LOOP
                IF version_row.published_at IS NOT NULL THEN
                    RAISE EXCEPTION 'published_version_immutable' USING ERRCODE = '23514';
                END IF;
            END LOOP;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END $$
        """)
        op.execute("""
        CREATE TRIGGER published_fields_guard BEFORE INSERT OR UPDATE OR DELETE ON form_fields
        FOR EACH ROW EXECUTE FUNCTION protect_published_fields()
        """)
    elif op.get_bind().dialect.name == "sqlite":
        for operation in ("UPDATE", "DELETE"):
            op.execute(f"""CREATE TRIGGER published_version_{operation.lower()}
                BEFORE {operation} ON form_versions WHEN OLD.published_at IS NOT NULL
                BEGIN SELECT RAISE(ABORT, 'published_version_immutable'); END""")
        for operation, references in (
            ("INSERT", ["NEW"]),
            ("UPDATE", ["OLD", "NEW"]),
            ("DELETE", ["OLD"]),
        ):
            condition = " OR ".join(
                f"EXISTS(SELECT 1 FROM form_versions WHERE id = {ref}.form_version_id AND published_at IS NOT NULL)"
                for ref in references
            )
            op.execute(f"""CREATE TRIGGER published_fields_{operation.lower()}
                BEFORE {operation} ON form_fields WHEN {condition}
                BEGIN SELECT RAISE(ABORT, 'published_version_immutable'); END""")
